
import { jsPDF } from 'jspdf';
import { SavedVariant, Material } from '../types';
import { SHOE_PARTS } from '../constants';

/**
 * Generates a PDF Document containing selected variants.
 * Format: Landscape, 1 Variant per page.
 * Layout: Image on Left (Clean), Material Specs on Right.
 * Logic: Dynamically adjusts spacing and columns to ensure all parts fit on one page.
 */
export const generatePDF = (variants: SavedVariant[], materials: Material[]) => {
  if (!variants || variants.length === 0) return;

  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  });

  variants.forEach((variant, index) => {
    if (index > 0) doc.addPage();

    // -- Header --
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(20, 20, 30);
    doc.text(variant.name, 20, 20);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const dateStr = new Date(variant.timestamp).toLocaleString();
    doc.text(`Created: ${dateStr}`, 20, 26);

    // -- Image (Left Side) --
    // Force 16:9 Aspect Ratio
    // We are now forcing the source snapshot to be 16:9 (e.g. 1920x1080)
    // So we should display it in a 16:9 box in the PDF to match.
    // Width: 120mm
    // Height: 120 * (9/16) = 67.5mm
    const imgWidth = 120;
    const imgHeight = 67.5;
    
    try {
      if (variant.thumbnail) {
        doc.addImage(variant.thumbnail, 'PNG', 20, 35, imgWidth, imgHeight);
      }
    } catch (e) {
      console.error("Failed to add image", e);
    }

    // -- Details (Right Side) --
    const startX = 150; // Shifted right slightly due to 16:9 image width (120 + 20 margin + 10 gap)
    const initialY = 45;
    
    // Title
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("Material Specifications", startX, 35);
    
    // Divider Line
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.line(startX, 38, 280, 38); // Span to right edge margin

    // -- Dynamic Layout Engine --
    const partKeys = Object.keys(variant.materials);
    const count = partKeys.length;
    
    // Available vertical space approx 150mm (from Y=45 to Y=195)
    const availableHeight = 150;
    
    let spacing = 12; // Default comfortable spacing
    let useTwoCols = false;
    let labelOffset = 40; // Indent for material name
    
    // 1. Check if standard spacing overflows
    if (count * spacing > availableHeight) {
       spacing = 8; // Condense vertical space
    }
    
    // 2. If still overflows, split into two columns
    if (count * spacing > availableHeight) {
       useTwoCols = true;
       spacing = 10; // Restore some breathing room for columns
       labelOffset = 30; // Tighter indent for columns
    }

    doc.setFontSize(10);

    partKeys.forEach((partId, i) => {
       // Get Data
       const partDef = SHOE_PARTS.find(p => p.id === partId);
       const partName = partDef ? partDef.name : partId;
       const matId = variant.materials[partId];
       const material = materials.find(m => m.id === matId);
       
       const matName = material ? material.name : 'Default';
       const matColor = material ? material.color : '#ffffff';

       // Calculate Position
       let x = startX;
       let y = initialY;

       if (useTwoCols) {
          const midpoint = Math.ceil(count / 2);
          if (i >= midpoint) {
             x = startX + 70; // Shift to second column (reduced slightly to fit)
             y = initialY + ((i - midpoint) * spacing);
          } else {
             y = initialY + (i * spacing);
          }
       } else {
          y = initialY + (i * spacing);
       }

       // Draw Part Name
       doc.setFont("helvetica", "bold");
       doc.setTextColor(40, 40, 40);
       doc.text(partName, x, y);

       // Draw Material Name
       doc.setFont("helvetica", "normal");
       doc.setTextColor(60, 60, 60);
       doc.text(`: ${matName}`, x + labelOffset, y);

       // Draw Color Info
       doc.setFontSize(8);
       doc.setTextColor(140, 140, 140);
       
       if (spacing >= 10) {
          // If enough space, put hex on next line for readability
          doc.text(matColor, x + labelOffset + 2, y + 4);
       } else {
          // If tight, put hex inline
          const width = doc.getTextWidth(`: ${matName}`);
          doc.text(`(${matColor})`, x + labelOffset + width + 3, y);
       }
       
       doc.setFontSize(10); // Reset for next item
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by NK 3D customization", 297 - 20, 200, { align: 'right' });
  });

  doc.save('nk-3d-design-collection.pdf');
};
